#!/bin/bash

SSHUSERNAME=username
SSHPASSWORD=UsersPassword
REMOTE_HOST=localhost
REMDIR=upload
## Optional
#IDENTITYFILE=/home/user/.ssh/id_rsa

###############
###############
export SSHUSER=${SSHUSERNAME}
export SSHPASS=${SSHPASSWORD}

function sftpfile {
   if [ ! -z ${REMDIR} ]; then
      CDDIR="cd ${REMDIR}"
   fi
   if [ ! -z ${IDENTITYFILE} ]; then
      SFTPCMD="sftp -oIdentityFile=\"${IDENTITYFILE}\""
   else
      SFTPCMD="sshpass -e sftp"
   fi
   $SFTPCMD -oBatchMode=no -b - ${SSHUSER}@${REMOTE_HOST} << !
${CDDIR}
put "${1}"
bye
!
}

function chkfile {
   if [ ! -z ${REMDIR} ]; then
      CDDIR="cd ${REMDIR}"
   fi
   REMFILE=`basename "${1}"`
   if [ ! -z ${IDENTITYFILE} ]; then
      SFTPCMD="sftp -oIdentityFile=\"${IDENTITYFILE}\""
   else
      SFTPCMD="sshpass -e sftp"
   fi
   $SFTPCMD -oBatchMode=no -b - ${SSHUSER}@${REMOTE_HOST} << !
${CDDIR}
ls ${REMFILE}
bye
!
}

function does-file-exist {
   SFTPOUTPUT=`chkfile "${1}" 2>&1`
   EXISTS=`echo ${SFTPOUTPUT} | grep "Can't ls:" | grep "not found" | wc -l`
   ## If EXISTS equals 1 then the file does not exist return 0
   if [ ${EXISTS} == 1 ]; then
      echo "0"
   else
      echo "1"
   fi
}
#################
#################

sftpfile test.txt >/dev/null 2>&1
does-file-exist test.txt
